# Generated by Django 4.0 on 2021-12-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('discription', models.TextField(max_length=500)),
                ('original_price', models.FloatField()),
                ('discound_price', models.FloatField()),
                ('category', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
